name: Fronius Solar API Emulator
version: "1.1.0"
slug: fronius_solar_api_emulator
description: Simuliert die Fronius Solar API V1 mit Wechselrichter, Batteriespeicher und Smart Meter basierend auf Home Assistant Sensordaten.
url: https://github.com/matze308/ha-solar-api-emulator
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
map:
  - config:rw
options:
  port: 8088
  log_level: info
  sensor_pv: sensor.solar_manager_power_pv
  sensor_power: sensor.solar_manager_power
  sensor_grid: sensor.solar_manager_power_grid
  sensor_soc: sensor.solar_manager_soc
  sensor_battery: sensor.solar_manager_power_battery
  sensor_production_today: sensor.solar_manager_production_today
schema:
  port: int
  log_level: list(debug|info|warning|error)
  sensor_pv: str
  sensor_power: str
  sensor_grid: str
  sensor_soc: str
  sensor_battery: str
  sensor_production_today: str
ports:
  8088/tcp: 8088
ports_description:
  8088/tcp: Fronius Solar API HTTP Port
init: false
hassio_api: true
homeassistant_api: true
hassio_role: default
auth_api: false
ingress: false
panel_icon: mdi:solar-power
